server:
  port: 8080
spring:
  application:
    name: service-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.6.169:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-core
          uri: lb://service-core
          predicates:
            - Path=/*/core/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**