server:
  port: 8120
spring:
  profiles:
    active: dev
  application:
    name: service-sms

  cloud:
    #微服务注册中心
    nacos:
      discovery:
        server-addr: 8.148.6.169:8848
  redis:
    host: 8.104.6.169
    port: 6379
    database: 0
    timeout: 5000 #对打等待时间，超时则抛出异常
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-idle: 8 #最大空闲连接
        max-wait: -1 #最大阻塞等待时间，负值表示没有限制
        min-idle: 0 #最小空闲连接

#阿里云短信服务
aliyun:
  sms:
    region-id: rose@1689918897409884.onaliyun.com
    key-id: LTAI5t6RFyran9E2x5nB13tE
    key-secret: l7BWKJLpuAa6zjE9nlJxszpIFAX4QJ
    template-code: 短信模板code
    sign-name: 模板签名
